### ISSUE TITLE
how to add newline in message

### ISSUE THREAD

**Issue by ChangYinShung** [louis70109/line-notify-action#2]
Produce Steps
1.add this to `yml`
``` text
    - name: notify message while success
      uses: louis70109/line-notify-action@master
      if : steps.buildAction.outcome == 'success'
      with:
        token: ${{ secrets.LINE_NOTIFY_TOKEN }}
        message: '\n WorkSpaceName:${{ val1 }} \n Version:${{val2 }} \n Message:Github build success'
```
2.The Result : 
![image](https://user-images.githubusercontent.com/2546026/168881313-8f74346c-9b67-4a49-9c00-f2adc6a1d85b.png)

-----------
Except Result :
'\n' cant create newline in line app ?
``` text
[BotName]
WorkSpaceName:SCHOOL.Works
Version:513.0.0
Message:
Github get an error while building stage
````

**Comment by louis70109** [comment]
@ChangYinShung could you try following?

```
- name: send message with image url
  uses: louis70109/line-notify-action@master
  with:
    token: ${{ secrets.LINE_NOTIFY_TOKEN }}
    message: |
      Hello World....
      This is new line for Notify.
```
